{
 "title": "HyFiVe - basic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Deployment",
    "label": "Deployment",
    "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\" )  \r\n  |> distinct(column: \"deployment_id\")  \r\n"
   }
  ]
 },
 "panels": [
  { "title": "Map View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Map View",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 21, "x": 2, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")"
    },
    {
     "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"longitude\")"
    },
    {
     "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pressurembar" } },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")"
      }
     ]
    },
    {
     "title": "Oxygen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pressurembar" } },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oxygen\")"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
      }
     ]
    },
    {
     "title": "Conductivity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "mS/cm" } },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conductivity\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> filter(fn: (r) => r[\"deployment_id\"] == \"$Deployment\")\r\n  |> map(fn: (r) => ({r with _value: (r._value -950.0) / -100.0}))\r\n"
      },
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"deployment_id\"] == \"$Deployment\")"
      }
     ]
    },
    {
     "title": "Conductivity",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> filter(fn: (r) => r[\"deployment_id\"] == \"$Deployment\")\r\n  |> map(fn: (r) => ({r with _value: (r._value -950.0) / -100.0}))"
      },
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"deployment_id\"] == \"$Deployment\")"
      }
     ]
    },
    {
     "title": "Oxygen",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> filter(fn: (r) => r[\"deployment_id\"] == \"$Deployment\")\r\n  |> map(fn: (r) => ({r with _value: (r._value -950.0) / -100.0}))"
      },
      {
       "query": "from(bucket: \"localhyfive\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netcdf\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oxygen\")\r\n  |> filter(fn: (r) => r[\"deployment_id\"] == \"$Deployment\")"
      }
     ]
    }
   ]
  }
 ]
}